### ISSUE TITLE
Header Block

### ISSUE THREAD

**Issue by pinkfloydx33** [webmotions/Azure.WebJobs.Extensions#1]
Noticeably missing is the Header block (`type=header`). Any chance you can add this in? 

I tried adding my own block type locally but I was getting blocked by the validators (either because of the hardcoded type lists or only because you only search the extension assembly for validators)

**Comment by DOMZE** [comment]
Hello,

I added a PR for this. Let me know if it satisfies you. If so I will merge and a dev package will be available

**Comment by pinkfloydx33** [comment]
@DOMZE thanks! I appreciate it. Will try out the Dev package tomorrow

**Comment by pinkfloydx33** [comment]
Verified that it works with Dev package. Thanks again!
