### ISSUE TITLE
Attribute cannot read from custom configuration sections

### ISSUE THREAD

**Issue by pinkfloydx33** [webmotions/Azure.WebJobs.Extensions#2]
Most bindings can read from a custom configuration location. For example, a `QueueTrigger` can be provided the Queue's name **directly** OR via the tokenized environment variable name (wrapped in "%"). Similarly, the Connection String property of the `QueueTrigger` expects the environment variable name of the connection string (not wrapped in percent signs)

```csharp
[QueueTrigger("MyQueueName")]
[QueueTrigger("%My:Config:Section%", Connection="My:Other:Config")]
```

It would be great if this feature could be added. Otherwise, it's impossible to support more than one (two-ish) configuration-driven slack binding(s) in a single application since you only look at `AzureWebJobsSlackWebHookUrl`

All you need is to inject an `INameResolver` into the binding provider and call the extension method `TryResolveWholeString` optionally followed by `INameResolver.Resolve` (depending on which formats you want to support). 

Essentially something like this:

```csharp
INameResolver resolver = ...; // inject in constructor

// check if it resolves and that the value is NOT the same as the originally. This will happen when no percent signs are found
// false is returned for mismatched percent signs only
if (resolver.TryResolveWholeString(valueFromAttribute, out var resolved) && resolved != valueFromAttribute) {
    WebHookUrl = resolved;
} else {
  // the else block is optional, but would cover the case where the user provided just `My:SectionName` (without percents)
  // and you want it to resolve as well (like the Connection String related Attribute properties)
   var temp = resolver.Resolve(valueFromAttribute);
   if (temp != null && temp != valueFromAttribute) {
      WebHookUrl = resolved;
   }
}

// if neither case is matched above, then you would use the original value, as Is
```

I'd be happy to submit a PR for this if you would accept one.

**Comment by DOMZE** [comment]
Yes, please do! Thank you for contributing

**Comment by pinkfloydx33** [comment]
@DOMZE I realized that this can be done much easier since these are binding attributes. The solution would simply be to add the `AutoResolve` attribute to the WebHookUrl/ApiKey properties (they're already on all the others). AutoResolve takes into account `%Syntax%` in addition to `{Syntax}` which means that the two properties could be fed into in a variety of way. I think that's the best/easiest thing to do. 

However, I haven't looked through the library enough. I don't know if you make any assumptions about those values that wouldn't make this a safe operation.

**Comment by DOMZE** [comment]
Let me check I will get back to you.

**Comment by DOMZE** [comment]
Hi @pinkfloydx33

In fact, AutoResolve would work on the attribute options. I have in the code
```csharp
var apiKey = Utility.FirstOrDefault(attribute.ApiKey, _options.ApiKey);
var webHookUrl = Utility.FirstOrDefault(attribute.WebHookUrl, _options.WebHookUrl);
```

which picks the value on a first base basis.

I've created a PR that includes this, including some small fixes and packages updates.

**Comment by pinkfloydx33** [comment]
PR looks good to me. I thank you for these changes. Definitely helps my overall use case. And thanks for a great library!

**Comment by DOMZE** [comment]
Package in Dev should be available. I will create the official package in the next few days.

Thank you for using it. Makes me happy!

**Comment by pinkfloydx33** [comment]
Dev package works as expected. Thanks again!

**Comment by DOMZE** [comment]
@pinkfloydx33 official 1.2.0 package is now available
