### ISSUE TITLE
Cannot Add SlackImageBlock to SlackMessage

### ISSUE THREAD

**Issue by sleeplessninja** [webmotions/Azure.WebJobs.Extensions#5]
Great binding library!  I am trying to add a SlackImageBlock to the slack message.  When the message is sent I am receiving this error log.

![image](https://user-images.githubusercontent.com/1628063/133800966-a3998bdd-5736-4267-9275-56d33f6ad763.png)

The image block is not recognized as a block.  Please advise.  Thank you!

here is a snippet of the code related to the error:
`var slackMessage = new SlackMessage();
            slackMessage.Text = "Alert Incoming!!";

            var sectionBlock1 = new SlackSectionBlock();
            sectionBlock1.Text = new SlackMarkdownText { Text = "*hello world" };
            sectionBlock1.Accessory = new SlackImageBlockElement
            {
                Url = new Uri("https://media.giphy.com/media/w567xuOsFbYiwnTooE/giphy.gif"),
                AlternateText = "Friday GIF"
            };
            slackMessage.Blocks.Add(sectionBlock1);
            
            var imageBlock = new SlackImageBlock()
            {
                AlternateText = "Friday GIF",
                Url = new Uri("https://media.giphy.com/media/w567xuOsFbYiwnTooE/giphy.gif"),
            };
            slackMessage.Blocks.Add(imageBlock);`

**Comment by DOMZE** [comment]
Hi!

Yes you are right, it's a bug in the slack message validator.

I've fixed the problem in version 1.2.1 available on NuGet.

Thanks for flagging and your support!

**Comment by bballmchick14** [comment]
Removed comment as not relevant.

**Comment by DOMZE** [comment]
@bballmchick14 is this related to this library? If so, please open a new issue :-)
